apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pmlinks
  annotations:
   volume.beta.kubernetes.io/storage-class: "erikube-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.5Gi
