apiVersion: v1
kind: Service
metadata:
  name: ldap-remote
  labels:
    app: opendj
spec:
  ports:
  - port: 1636
  selector:
    app: opendj

---
apiVersion: v1
kind: Service
metadata:
  name: ldap-local
  labels:
    app: opendj
spec:
  ports:
  - port: 1636
  selector:
    app: opendj

---
apiVersion: v1
kind: Service
metadata:
  name: opendj
  labels:
    app: opendj
spec:
  ports:
  - port: 1636
  selector:
    app: opendj


