apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mdt
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 131.160.142.101
    path: "/ericsson/mdt"
  persistentVolumeReclaimPolicy: Retain
