apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-configmgt
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 131.160.142.101
    path: "/ericsson/config_mgt"
  persistentVolumeReclaimPolicy: Retain
