apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-upgind
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 131.160.142.101
    path: "/ericsson/config_mgmt_upgind"
  persistentVolumeReclaimPolicy: Retain
