apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-tfd
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 131.160.142.101
    path: "/ericsson/tfd_cli_output"
  persistentVolumeReclaimPolicy: Retain
