apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-alex
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 131.160.142.101
    path: "/ericsson/alex"
  persistentVolumeReclaimPolicy: Retain
