apiVersion: v1
kind: Service
metadata:
  name: svc-1-fmserv
spec:
  ports:
    - name: jboss
      port: 8080
      targetPort: 8080
    - name: ejb
      port: 4447
      targetPort: 4447
  selector:
    app: svc-1-fmserv
