apiVersion: apps/v1
kind: Deployment
metadata:
  name: gp
spec:
  selector:
    matchLabels:
      app: gp
  replicas: 1
  template:
    metadata:
      labels:
        app: gp
    spec:
#      initContainers:
      containers:
      - name: gp
        #image: armdocker.rnd.ericsson.se/proj-enmk8spoc/neo-cypher:0.0.4
        image: 213418823860.dkr.ecr.us-east-1.amazonaws.com/enmpoc1-registry:cyphershell-alpine
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
#          - bash configure.sh;
          - ln -s /gp/global.properties /ericsson/tor/data/global.properties.mick;while true; do sleep 300;done;
        volumeMounts:
          - name: pv-gp
            mountPath: /gp
          - name: pv-data
            mountPath: /ericsson/tor/data
      volumes:
        - name: pv-gp
          configMap:
            name: gpconfigmap
        - name: pv-data
          persistentVolumeClaim:
            claimName: data
