kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: norollback
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs-general"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
