apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdt
  annotations:
   volume.beta.kubernetes.io/storage-class: "efs-models"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
