apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  labels:
    name: nginx-example
spec:
  selector:
    app: haproxy
  type: LoadBalancer
  ports:
  - name: http
    port: 443
    targetPort: 443
