apiVersion: v1
kind: Service
metadata:
  name: mick
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: (https|http|ssl|tcp)
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: ejb
      port: 4447
      targetPort: 4447
  selector:
    app: httpd
  type: LoadBalancer
