kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: role-read-services-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
 kind: Role
 name: role-read-services
 apiGroup: rbac.authorization.k8s.io
