apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-tmp
  annotations:
    volume.beta.kubernetes.io/storage-class: "gp2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
