apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-hcdumps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      enmnfs: nfs-hcdumps
  storageClassName: ""
