apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-sdn
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      enmnfs: nfs-sdn
  storageClassName: ""
