apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-smrs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      enmnfs: nfs-smrs
  storageClassName: ""
