apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pm2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      enmnfs: nfs-pm2
  storageClassName: ""
