apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-alex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      enmnfs: nfs-alex
  storageClassName: ""
