apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-netlog
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      enmnfs: nfs-netlog
  storageClassName: ""
