apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-norollback
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      enmnfs: nfs-norollback
  storageClassName: ""
