apiVersion: v1
kind: Service
metadata:
  name: mspm
spec:
  ports:
    - name: jboss
      port: 8080
      targetPort: 8080
    - name: ejb
      port: 4447
      targetPort: 4447
    - name: med-1
      port: 4569
      targetPort: 4569
    - name: med-2
      port: 4576
      targetPort: 4576
  selector:
    app: mspm
