apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mspm-ingress-l4
  annotations:
    protocol: TCP
    layer: L4
spec:
  backend:
    serviceName: mspm-corba-service
    servicePort: 58151
