apiVersion: v1
kind: Service
metadata:
  name: httpd-nodeport
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: ejb
      port: 4447
      targetPort: 4447
    - name: modcluster
      port: 8666
      targetPort: 8666
  type: NodePort
  selector:
    app: httpd
