
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: klvs-manager-role
rules:
- apiGroups:
  - routers.lvsrouter.ericsson.com
  resources:
  - klvsrouters
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - routers.lvsrouter.ericsson.com
  resources:
  - klvsrouters/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - service
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - service
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch