apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossiprouter-cache
spec:
  selector:
    matchLabels:
      app: gossiprouter-cache
  replicas: 1
  template:
    metadata:
      labels:
        app: gossiprouter-cache
    spec:
      containers:
      - name: gossiprouter-cache
        resources:
          requests:
            memory: "2Gi"
        image: 213418823860.dkr.ecr.us-east-1.amazonaws.com/enmpoc1-registry:gossip-rhel6jboss
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            value: "12002"
          - name: GOSSIP_ROUTER_USAGE
            value: "caches"
        ports:
          - containerPort: 12001
          - containerPort: 12002
          - containerPort: 9990
          - containerPort: 8009
          - containerPort: 9999
          - containerPort: 8080
          - containerPort: 4447
          - containerPort: 9999
        command: ["/entrypoint.sh"]
        args:
          - -bind_addr $(POD_IP) -port $(PORT)
        volumeMounts:
          - name: pv-data
            mountPath: /ericsson/tor/data
          - name: pv-dumps
            mountPath: /ericsson/enm/dumps
          - name: pv-norollback
            mountPath: /ericsson/no_rollback
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: data
        - name: pv-norollback
          persistentVolumeClaim:
            claimName: norollback
        - name: pv-dumps
          persistentVolumeClaim:
            claimName: dumps

