apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossiprouter-remoting
spec:
  selector:
    matchLabels:
      app: gossiprouter-remoting
  replicas: 1
  template:
    metadata:
      labels:
        app: gossiprouter-remoting
    spec:
      containers:
      - name: gossiprouter-remoting
        resources:
          requests:
            memory: "2Gi"
        image: dockerregistry:5000/rhel6-gossip-test
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONFIG_FILE
            value: "/ericsson/3pp/jggossiprouters/lib_for_remoting/log4j.properties"
          - name: CLASSPATH
            value: "/ericsson/3pp/jggossiprouters/lib_for_remoting/"
          - name: PORT
            value: "12002"
        ports:
          - containerPort: 12001
          - containerPort: 12002
          - containerPort: 9990
          - containerPort: 8009
          - containerPort: 9999
          - containerPort: 8080
          - containerPort: 4447
          - containerPort: 9999
#        command: ["/bin/sh", "-c"]
#        args:
 #         - while true; do sleep 300;done;
        args:
          - -Dlog4j.configuration=file:$CONFIG_FILE -cp $CLASSPATH/jgroups-3.6.1.Final.jar org.jgroups.stack.GossipRouter -bind_addr $POD_IP -port $PORT
        volumeMounts:
          - name: pv-data
            mountPath: /ericsson/tor/data
          - name: pv-dumps
            mountPath: /ericsson/enm/dumps
          - name: pv-norollback
            mountPath: /ericsson/no_rollback
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: data
        - name: pv-norollback
          persistentVolumeClaim:
            claimName: no-rollback
        - name: pv-dumps
          persistentVolumeClaim:
            claimName: hcdumps

