apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpserv-deployment
spec:
  selector:
    matchLabels:
      app: wpserv
  replicas: 1
  template:
    metadata:
      labels:
        app: wpserv
    spec:
      containers:
      - name: wpserv
        resources:
          requests:
            memory: "3Gi"
        image: 213418823860.dkr.ecr.us-east-1.amazonaws.com/enmpoc1-registry:wpserv-rhel6jboss
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
          - containerPort: 8443
          - containerPort: 9990
          - containerPort: 9999
          - containerPort: 4447
          - containerPort: 45145  
          - containerPort: 9990   
          - containerPort: 3528   
          - containerPort: 45513  
          - containerPort: 8009   
          - containerPort: 8301   
          - containerPort: 44634  
          - containerPort: 44379  
          - containerPort: 12987
          - containerPort: 9443
          - containerPort: 4712
          - containerPort: 4713
          - containerPort: 3528
          - containerPort: 3529
          - containerPort: 55501
          - containerPort: 55500
        command: ["/bin/sh", "-c"]
        args:
          - bash /var/tmp/wpserv_config.sh; while true; do sleep 10;done;
        volumeMounts:
          - name: pv-data
            mountPath: /ericsson/tor/data
          - name: pv-mdt
            mountPath: /etc/opt/ericsson/ERICmodeldeployment
          - name: pv-custom
            mountPath: /ericsson/custom
          - name: pv-dumps
            mountPath: /ericsson/enm/dumps
          - name: pv-dlms
            mountPath: /ericsson/enm/dlms/history/data
          - name: pv-shared
            mountPath: /ericsson/home
          - name: pv-ddcdata
            mountPath: /var/ericsson/ddc_data
          - name: pv-norollback
            mountPath: /ericsson/no_rollback
          - name: pv-batch
            mountPath: /ericsson/batch
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: data
        - name: pv-dumps
          persistentVolumeClaim:
            claimName: dumps
        - name: pv-mdt
          persistentVolumeClaim:
            claimName: mdt
        - name: pv-shared
          persistentVolumeClaim:
            claimName: shared
        - name: pv-custom
          persistentVolumeClaim:
            claimName: custom
        - name: pv-dlms
          persistentVolumeClaim:
            claimName: dlms
        - name: pv-ddcdata
          persistentVolumeClaim:
            claimName: ddcdata
        - name: pv-norollback
          persistentVolumeClaim:
            claimName: norollback
        - name: pv-batch
          persistentVolumeClaim:
            claimName: batch
