apiVersion: apps/v1
kind: Deployment
metadata:
  name: secserv-deployment
spec:
  selector:
    matchLabels:
      app: secserv
  replicas: 1
  template:
    metadata:
      labels:
        app: secserv
    spec:
      containers:
      - name: secserv
        resources:
          requests:
            memory: "6Gi"
        image: dockerregistry:5000/rhel6-secserv
        ports:
          - containerPort: 22
          - containerPort: 56450
          - containerPort: 56453
          - containerPort: 56422
          - containerPort: 9990 
          - containerPort: 46055
          - containerPort: 56456
          - containerPort: 57193
          - containerPort: 8009 
          - containerPort: 63178
          - containerPort: 58156
          - containerPort: 56430
          - containerPort: 55631
          - containerPort: 9999 
          - containerPort: 8080 
          - containerPort: 56433
          - containerPort: 63218
          - containerPort: 56403
          - containerPort: 54200
          - containerPort: 56409
          - containerPort: 8090 
          - containerPort: 8091 
          - containerPort: 63228
          - containerPort: 8092 
          - containerPort: 8093 
          - containerPort: 56415
          - containerPort: 4447
          - containerPort: 55501
          - containerPort: 55500
        command: ["/bin/sh", "-c"]
        args:
          - bash /var/tmp/secserv_config.sh; while true; do sleep 300;done;
        volumeMounts:
          - name: data
            mountPath: /ericsson/tor/data
          - name: pmul
            mountPath: /ericsson/ul_spectrum_files
          - name: smrs
            mountPath: /ericsson/tor/smrs
          - name: mdt
            mountPath: /etc/opt/ericsson/ERICmodeldeployment      
          - name: home
            mountPath: /home/shared
          - name: custom
            mountPath: /ericsson/custom
          - name: dumps
            mountPath: /ericsson/enm/dumps
          - name: dlms
            mountPath: /ericsson/enm/dlms/history/data
          - name: batch
            mountPath: /ericsson/batch
          - name: norollback
            mountPath: /ericsson/no_rollback
          - name: configmgt
            mountPath: /ericsson/config_mgt
          - name: pm1
            mountPath: /ericsson/pmic1
          - name: pm2
            mountPath: /ericsson/pmic2
          - name: pmlinks
            mountPath: /ericsson/symvol
          - name: upgind
            mountPath: /ericsson/configuration_management/UpgradeIndependence
      volumes:
        - name: configmgt
          nfs:
            server: nfsconfigmgt
            path: "/ericsson/config_mgt"
        - name: pm1
          nfs:
            server: nfspm1
            path: "/ericsson/pm1"
        - name: pm2
          nfs:
            server: nfspm2
            path: "/ericsson/pm2"
        - name: pmlinks
          nfs:
            server: nfspmlinks
            path: "/ericsson/pmlinks1"
        - name: upgind
          nfs:
            server: nfsupgind
            path: "/ericsson/config_mgmt_upgind"
        - name: smrs
          nfs:
            server: nfssmrs
            path: "/ericsson/smrs"
        - name: pmul
          nfs:
            server: nfspmul
            path: "/ericsson/pmul"
        - name: data
          nfs:
            server: nfsdata
            path: "/ericsson/data"
        - name: dumps
          nfs:
            server: nfshcdumps
            path: "/ericsson/hcdumps"
        - name: mdt
          nfs:
            server: nfsmdt
            path: "/ericsson/mdt"
        - name: home
          nfs:
            server: nfshome
            path: "/ericsson/home"
        - name: custom
          nfs:
            server: nfscustom
            path: "/ericsson/custom"
        - name: dlms
          nfs:
            server: nfsdlms
            path: "/ericsson/dlms"
        - name: batch
          nfs:
            server: nfsbatch
            path: "/ericsson/batch"
        - name: norollback
          nfs:
            server: nfsnorollback
            path: "/ericsson/no_rollback"
