apiVersion: v1
kind: Service
metadata:
  name: openidm
spec:
  ports:
    - name: secure
      port: 8445
      targetPort: 8445
    - name: someport
      port: 8446
      targetPort: 8443
    - name: unsecure
      port: 8085
      targetPort: 8085
  selector:
    app: openidm
