apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
  serviceName: consul
  replicas: 3
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: 213418823860.dkr.ecr.us-east-1.amazonaws.com/enmpoc1-registry:consul-rhel6base
        ports:
          - containerPort: 8500
          - containerPort: 8443
          - containerPort: 8400
          - containerPort: 8301
          - containerPort: 8302
          - containerPort: 8600
          - containerPort: 53
          - containerPort: 80
          - containerPort: 443
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command: ["consul"]
        args:
          - "agent"
          - "-advertise=$(POD_IP)"
          - "-node=$(POD_NAME)"
          - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
          - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
          - "-retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
          - "-config-dir=/ericsson/consul/config"
        volumeMounts:
          - name: data
            mountPath: /ericsson/data
          - name: config
            mountPath: /ericsson/consul/config
      volumes:
        - name: config
          configMap:
            name: consul-server
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: "gp2"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
