apiVersion: v1
kind: Service
metadata:
  name: brianservice
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: sometcp
      port: 8080
      targetPort: 8080
    - name: someothertcp
      port: 7070
      targetPort: 7070
  selector:
    app: brianserver

