apiVersion: v1
kind: Service
metadata:
  name: gossiprouter-cache
spec:
  ports:
    - name: caches
      port: 12002
      targetPort: 12002
  selector:
    app: gossiprouter-cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossiprouter-cache
spec:
  selector:
    matchLabels:
      app: gossiprouter-cache
  replicas: 1
  template:
    metadata:
      labels:
        app: gossiprouter-cache
    spec:
      containers:
      - name: gossiprouter-cache
        resources:
          requests:
            memory: "2Gi"
        image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/eric-enmsg-gossiprouter
        imagePullPolicy: Always
#        livenessProbe:
#          httpGet:
#            port: 12987
#          initialDelaySeconds: 300
#          timeoutSeconds: 10
#          periodSeconds: 30
#          failureThreshold: 2
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            value: "12002"
          - name: GOSSIP_ROUTER_USAGE
            value: "caches"
        ports:
          - containerPort: 12001
          - containerPort: 12002
          - containerPort: 9990
          - containerPort: 8009
          - containerPort: 9999
          - containerPort: 8080
          - containerPort: 4447
          - containerPort: 9999
        args:
          - -bind_addr $(POD_IP) -port $(PORT)
        volumeMounts:
          - name: nfs-hcdumps
            mountPath: /ericsson/enm/dumps
      volumes:
        - name: nfs-hcdumps
          persistentVolumeClaim:
            claimName: nfs-hcdumps
