kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sentinel
  annotations:
    volume.beta.kubernetes.io/storage-class: "erikube-cinder"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

