apiVersion: v1
kind: Service
metadata:
  name: lvs-controller-manager-service
  labels:
    control-plane: lvs-controller-manager
    lvs-controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: lvs-controller-manager
    lvs-controller-tools.k8s.io: "1.0"
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lvs-controller-manager
  labels:
    control-plane: lvs-controller-manager
    lvs-controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: lvs-controller-manager
      lvs-controller-tools.k8s.io: "1.0"
  serviceName: lvs-controller-manager-service
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        control-plane: lvs-controller-manager
        lvs-controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /manager
        image: k8s-registry.eccd.local/controller:latest
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
