dependencies:
  - name: eric-enm-globalproperties
    repository: "@local"
    version: 1.0.1
    condition: eric-enm-globalproperties.enabled
  - name: nfs-client-provisioner
    repository: "@local"
    version: 1.2.0
    condition: nfs-client-provisioner.enabled
  - name: eric-enm-nfspvc
    repository: "@local"
    version: 1.0.1
    condition: eric-enm-nfspvc.enabled
  - name: eric-enm-serviceroles
    repository: "@local"
    version: 1.0.1
    condition: eric-enm-serviceroles.enabled
  - name: eric-enmsg-gossiprouter-cache
    repository: "@local"
    version: 0.1.0
    condition: eric-enmsg-gossiprouter-cache.enabled
  - name: eric-enmsg-gossiprouter-remoting
    repository: "@local"
    version: 0.1.0
    condition: eric-enmsg-gossiprouter-remoting.enabled
  - name: eric-enmsg-jmsserver
    repository: "@local"
    version: 0.1.0
    condition: eric-enmsg-jmsserver.enabled
  - name: eric-enmsg-modelserv
    repository: "@local"
    version: 0.1.0
    condition: eric-enmsg-modelserv.enabled
  - name: eric-enmsg-opendj
    repository: "@local"
    version: 0.1.0
    condition: eric-enmsg-opendj.enabled
  - name: eric-enmsg-postgres
    repository: "@local"
    version: 0.1.0
    condition: eric-enmsg-postgres.enabled
  - name: eric-enmsg-sentinel
    repository: "@local"
    version: 0.1.0
    condition: eric-enmsg-sentinel.enabled
  - name: eric-enmsg-serviceregistry
    repository: "@local"
    version: 0.1.0
    condition: eric-enmsg-serviceregistry.enabled
  - name: eric-enm-elasticsearch
    repository: "@local"
    version: 0.1.0
    condition: eric-enm-elasticsearch.enabled
  - name: neo4j
    repository: "@local"
    version: 0.7.2
    condition: neo4j.enabled