apiVersion: apps/v1
kind: Deployment
metadata:
  name: netex-deployment
spec:
  selector:
    matchLabels:
      app: netex
  replicas: 1
  template:
    metadata:
      labels:
        app: netex
    spec:
      containers:
      - name: netex
        resources:
          requests:
            memory: "2Gi"
        image: dockerregistry:5000/rhel6-netex
        ports:
          - containerPort: 8080
          - containerPort: 9990
          - containerPort: 9999
          - containerPort: 4447
          - containerPort: 60551
          - containerPort: 34789
          - containerPort: 3528
          - containerPort: 8009
          - containerPort: 58156
          - containerPort: 47246
          - containerPort: 54200
          - containerPort: 12987
          - containerPort: 55501
          - containerPort: 55500
        command: ["/bin/sh", "-c"]
        args:
          - bash /var/tmp/netex_config.sh; while true; do sleep 300;done;
        volumeMounts:
          - name: data
            mountPath: /ericsson/tor/data
          - name: mdt
            mountPath: /etc/opt/ericsson/ERICmodeldeployment      
          - name: home
            mountPath: /home/shared
          - name: custom
            mountPath: /ericsson/custom
          - name: dumps
            mountPath: /ericsson/enm/dumps
          - name: dlms
            mountPath: /ericsson/enm/dlms/history/data
          - name: batch
            mountPath: /ericsson/batch
          - name: norollback
            mountPath: /ericsson/no_rollback
      volumes:
        - name: data
          nfs:
            server: nfsdata
            path: "/ericsson/data"
        - name: dumps
          nfs:
            server: nfshcdumps
            path: "/ericsson/hcdumps"
        - name: mdt
          nfs:
            server: nfsmdt
            path: "/ericsson/mdt"
        - name: home
          nfs:
            server: nfshome
            path: "/ericsson/home"
        - name: custom
          nfs:
            server: nfscustom
            path: "/ericsson/custom"
        - name: dlms
          nfs:
            server: nfsdlms
            path: "/ericsson/dlms"
        - name: batch
          nfs:
            server: nfsbatch
            path: "/ericsson/batch"
        - name: norollback
          nfs:
            server: nfsnorollback
            path: "/ericsson/no_rollback"
