apiVersion: v1
kind: Service
metadata:
  name: app-d
  labels:
    app: app-d
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: app-d
