apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
  - port: 5432
    name: postgres
  - port: 22
    name: ssh
  selector:
    app: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql01
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  - port: 22
    name: ssh
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: haproxy-wait
        resources:
        image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/eric-enm-init-container
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - 'bash /var/tmp/check_service.sh -s opendj -n default'
      containers:
      - name: postgres
        image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/eric-enmsg-postgres
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            port: 12987
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 2
        ports:
          - containerPort: 5432
          - containerPort: 22
        command: ["/bin/sh", "-c"]
        args:
          - bash /var/tmp/postgres_config.sh; while true; do sleep 300;done;
        securityContext:
          privileged: true
        volumeMounts:
          - name: nfs-gp
            mountPath: /gp
          - name: nfs-data
            mountPath: /ericsson/tor/data
          - name: nfs-mdt
            mountPath: /etc/opt/ericsson/ERICmodeldeployment
          - name: nfs-custom
            mountPath: /ericsson/custom
          - name: nfs-hcdumps
            mountPath: /ericsson/enm/dumps
          - name: nfs-dlms
            mountPath: /ericsson/enm/dlms/history/data
          - name: nfs-batch
            mountPath: /ericsson/batch
          - name: nfs-norollback
            mountPath: /ericsson/no_rollback
          - name: nfs-configmgt
            mountPath: /ericsson/config_mgt
          - name: nfs-home
            mountPath: /ericsson/home
          - name: nfs-cron
            mountPath: /ericsson/vmcrons
          - name: pv-postgres
            mountPath: /ericsson/postgres
      volumes:
        - name: nfs-gp
          configMap:
            name: gpphysical
        - name: nfs-data
          persistentVolumeClaim:
            claimName: nfs-data
        - name: nfs-mdt
          persistentVolumeClaim:
            claimName: nfs-mdt
        - name: nfs-custom
          persistentVolumeClaim:
            claimName: nfs-custom
        - name: nfs-hcdumps
          persistentVolumeClaim:
            claimName: nfs-hcdumps
        - name: nfs-dlms
          persistentVolumeClaim:
            claimName: nfs-dlms
        - name: nfs-batch
          persistentVolumeClaim:
            claimName: nfs-batch
        - name: nfs-norollback
          persistentVolumeClaim:
            claimName: nfs-norollback
        - name: nfs-configmgt
          persistentVolumeClaim:
            claimName: nfs-configmgt
        - name: nfs-home
          persistentVolumeClaim:
            claimName: nfs-home
        - name: nfs-cron
          persistentVolumeClaim:
            claimName: nfs-cron
  volumeClaimTemplates:
    - metadata:
        name: pv-postgres
      spec:
        storageClassName: "erikube-cinder"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi

