apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossiprouter-deployment
spec:
  selector:
    matchLabels:
      app: gossiprouter
  replicas: 1
  template:
    metadata:
      labels:
        app: gossiprouter
    spec:
      containers:
      - name: gossiprouter
        resources:
          requests:
            memory: "2Gi"
        image: dockerregistry:5000/rhel6-gossip
        ports:
          - containerPort: 12001
          - containerPort: 12002
          - containerPort: 9990 
          - containerPort: 8009 
          - containerPort: 9999 
          - containerPort: 8080 
          - containerPort: 4447 
          - containerPort: 9999
          
        command: ["/bin/bash"]
        args: ["-c","while true; do sleep 10;done"]
        volumeMounts:
          - name: data
            mountPath: /ericsson/tor/data
          - name: dumps
            mountPath: /ericsson/enm/dumps
          - name: norollback
            mountPath: /ericsson/no_rollback
      volumes:
        - name: data
          nfs:
            server: nfsdata
            path: "/ericsson/data"
        - name: dumps
          nfs:
            server: nfshcdumps
            path: "/ericsson/hcdumps"
        - name: norollback
          nfs:
            server: nfsnorollback
            path: "/ericsson/no_rollback"
