apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nfs-client-provisioner.fullname" . }}
  labels:
    app: {{ template "nfs-client-provisioner.name" . }}
    chart: {{ template "nfs-client-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: {{ template "nfs-client-provisioner.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nfs-client-provisioner.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "nfs-client-provisioner.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: {{ template "nfs-client-provisioner.provisionerName" . }}
            - name: NFS_SERVER
              value: {{ .Values.global.nfsprovisioner.server }}
            - name: NFS_PATH
              value: {{ .Values.global.nfsprovisioner.path }}
      volumes:
        - name: nfs-client-root
{{- if .Values.buildMode }}
          emptyDir: {}
{{- else if .Values.nfs.mountOptions }}
          persistentVolumeClaim:
            claimName: pvc-{{ template "nfs-client-provisioner.fullname" . }}
{{- else }}
          nfs:
            server: {{ .Values.global.nfsprovisioner.server }}
            path: {{ .Values.global.nfsprovisioner.path }}
{{- end }}
