## eric-enm-elasticsearch image version

global:
  registry:
    url: armdocker.rnd.ericsson.se
    pullSecret:
  replicas-eric-enmsg-opendj: 1
  ingress:
    enmhost:
  persistentVolumeClaim:
    storageClass:


# Number of replicas(pods) to deploy
replicas-eric-enm-elasticsearch: 1

images:
  eric-enm-elasticsearch:
    name: eric-enm-elasticsearch
    tag: latest
    command: "[ '/bin/sh', '-c', 'bash /var/tmp/SERVICENAME_config.sh; while true; do sleep 300;done;' ]"
  waitInitContainer:
    enabled: false
    name: eric-enm-init-container
    tag: latest
    command: "[ '/bin/sh', '-c', 'bash /var/tmp/check_service.sh -s WAITSERVICE' ]"
  enmInitContainer:
    enabled: false
    name: eric-enm-init-container
    tag: latest
    command: "[ '/bin/sh', '-c', 'bash configure.sh;' ]"

imageCredentials:
  repoPath: proj_oss_releases/enm 
  pullPolicy: Always
  registry:
    url:
    pullSecret:

## Persist data to a persistent volume
  ## database data Persistent Volume Storage Class
persistentVolumeClaim:
  enabled: true
  storageClass: "gp2"
  size: 5Gi

# LivenessProbe Health Check configuration.
livenessProbe:
  enabled: true
  httpPort: 12987
  initialDelaySeconds: 600
  timeoutSeconds: 15
  periodSeconds: 30
  failureThreshold: 1

readinessProbe:
  enabled: true
  httpPort: 12987
  initialDelaySeconds: 120
  periodSeconds: 30
  timeoutSeconds: 15
  failureThreshold: 1

# Extra Annotations to be added to pod
podAnnotations: {}

## Tolerations for pod assignment
### ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Affinity for pod assignment
### ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

# Constrain which nodes your pod is eligible to be scheduled on
### ref:  https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature
nodeAffinity: {}

### ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#pod-priority
priorityClassName: ""

## Node selector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

#https://kubernetes.io/docs/reference/federation/extensions/v1beta1/definitions/#_v1beta1_deploymentstrategy
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
