apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: dockerregistry:5000/rhel6-consul
        ports:
          - containerPort: 8500
          - containerPort: 8443
          - containerPort: 8400
          - containerPort: 8301
          - containerPort: 8302
          - containerPort: 8600
          - containerPort: 53
          - containerPort: 80
          - containerPort: 443
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.PodIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
          - "agent"
          - "-advertise_addr=$(POD_IP)"
          - "-bootstrap_expect=3"
          - "-datacenter=dc1"
          - "-retry_join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
          - "-retry_join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
          - "-retry_join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
          - "-config-file=/ericsson/consul/config/server.json"
          - "-domain=cluster.local"
        volumeMounts:
          - name: kv-data
            mountPath: /ericsson/consul/data
          - name: config
            mountPath: /ericsson/consul/config

