apiVersion: v1
kind: Service
metadata:
  name: smrsserv
spec:
  ports:
    - name: jboss
      port: 8080
      targetPort: 8080
    - name: ejb
      port: 4447
      targetPort: 4447
    - name: ssh
      port: 22
      targetPort: 22
  selector:
    app: smrs
