apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    enmnfs: "nfs-amos"
  name: nfs-amos
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 131.160.142.101
    path: "/ericsson/amos"
  persistentVolumeReclaimPolicy: Retain
