apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    enmnfs: "nfs-dlms"
  name: nfs-dlms
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 131.160.142.101
    path: "/ericsson/dlms"
  persistentVolumeReclaimPolicy: Retain
