apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    enmnfs: "nfs-ddcdata"
  name: nfs-ddcdata
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 131.160.142.101
    path: "/ericsson/ddc_data"
  persistentVolumeReclaimPolicy: Retain
