apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    enmnfs: "nfs-home"
  name: nfs-home
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 131.160.142.101
    path: "/ericsson/home"
  persistentVolumeReclaimPolicy: Retain
