apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    enmnfs: "nfs-hcdumps"
  name: nfs-hcdumps
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 131.160.142.101
    path: "/ericsson/hcdumps"
  persistentVolumeReclaimPolicy: Retain
