apiVersion: v1
kind: Service
metadata:
  name: models
  labels:
    name: models
spec:
  clusterIP: None
  ports:
    - name: port1
      port: 34371
      targetPort: 34371
    - name: port2
      port: 36869
      targetPort: 36869
  selector:
    app: models
