apiVersion: apps/v1
kind: Deployment
metadata:
  name: uiserv-micro-deployment
spec:
  selector:
    matchLabels:
      app: uiserv-micro
  replicas: 1
  template:
    metadata:
      labels:
        app: uiserv-micro
    spec:
      containers:
      - name: httpd
        image: 152254703525.dkr.ecr.eu-west-1.amazonaws.com/eirepoc1-registry:httpd-micro-rhel6basejava8
        imagePullPolicy: Always
#        livenessProbe:
#          httpGet:
#            port: 12987
#          initialDelaySeconds: 300
#          timeoutSeconds: 10
#          periodSeconds: 30
#          failureThreshold: 2
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 22
          - containerPort: 123
          - containerPort: 8666
          - containerPort: 4447
        command: ["/bin/sh", "-c"]
        args:
          - while true; do sleep 300;done;
        volumeMounts:
          - name: pv-gp
            mountPath: /gp
          - name: pv-data
            mountPath: /ericsson/tor/data
          - name: pv-smrs
            mountPath: /ericsson/tor/smrs
          - name: pv-mdt
            mountPath: /etc/opt/ericsson/ERICmodeldeployment
          - name: pv-shared
            mountPath: /ericsson/home
          - name: pv-custom
            mountPath: /ericsson/custom
          - name: pv-dumps
            mountPath: /ericsson/enm/dumps
          - name: pv-dlms
            mountPath: /ericsson/enm/dlms/history/data
          - name: pv-batch
            mountPath: /ericsson/batch
          - name: pv-norollback
            mountPath: /ericsson/tor/no_rollback
          - name: pv-alex
            mountPath: /ericsson/enm/alex
      - name: uiserv
        resources:
          requests:
            memory: "4Gi"
        image: 152254703525.dkr.ecr.eu-west-1.amazonaws.com/eirepoc1-registry:uiserv-rhel6jbossjava8
        imagePullPolicy: Always
#        livenessProbe:
#          httpGet:
#            port: 12987
#          initialDelaySeconds: 300
#          timeoutSeconds: 10
#          periodSeconds: 30
#          failureThreshold: 2
        ports:
          - containerPort: 35020
          - containerPort: 55200
          - containerPort: 42628
          - containerPort: 47460
          - containerPort: 56164
          - containerPort: 54949
          - containerPort: 8009
          - containerPort: 55631
          - containerPort: 46001
          - containerPort: 54200
          - containerPort: 12987
          - containerPort: 63167
          - containerPort: 8080
          - containerPort: 9990
          - containerPort: 4447
          - containerPort: 9999
          - containerPort: 56164
          - containerPort: 3528
          - containerPort: 58156
          - containerPort: 46001
          - containerPort: 54200
          - containerPort: 12987
          - containerPort: 63167
          - containerPort: 7600
          - containerPort: 57600
          - containerPort: 9443
          - containerPort: 4712
          - containerPort: 4713
          - containerPort: 3528
          - containerPort: 3529
          - containerPort: 55501
          - containerPort: 55500
          - containerPort: 35020
          - containerPort: 44004
          - containerPort: 56164
          - containerPort: 54949
          - containerPort: 8009
          - containerPort: 58156
          - containerPort: 55631
          - containerPort: 46001
          - containerPort: 54200
          - containerPort: 12987
          - containerPort: 63167
          - containerPort: 46000
          - containerPort: 55601
          - containerPort: 46002
          - containerPort: 58171
          - containerPort: 63165
          - containerPort: 63166
          - containerPort: 56162
          - containerPort: 56163
          - containerPort: 30200
          - containerPort: 50559
          - containerPort: 55181
          - containerPort: 55200
          - containerPort: 5445
          - containerPort: 5455
          - containerPort: 22
          - containerPort: 123
        command: ["/bin/sh", "-c"]
        args:
          - while true; do sleep 300;done;
        volumeMounts:
          - name: pv-gp
            mountPath: /gp
          - name: pv-data
            mountPath: /ericsson/tor/data
          - name: pv-mdt
            mountPath: /etc/opt/ericsson/ERICmodeldeployment
          - name: pv-netlog
            mountPath: /ericsson/netlog
          - name: pv-custom
            mountPath: /ericsson/custom
          - name: pv-dumps
            mountPath: /ericsson/enm/dumps
          - name: pv-dlms
            mountPath: /ericsson/enm/dlms/history/data
          - name: pv-batch
            mountPath: /ericsson/batch
          - name: pv-norollback
            mountPath: /ericsson/no_rollback
          - name: pv-configmgt
            mountPath: /ericsson/config_mgt
          - name: pv-pm1
            mountPath: /ericsson/pmic1
          - name: pv-pm2
            mountPath: /ericsson/pmic2
          - name: pv-pmlinks
            mountPath: /ericsson/symvol
          - name: pv-upgind
            mountPath: /ericsson/configuration_management/UpgradeIndependence
          - name: pv-ddcdata
            mountPath: /var/ericsson/ddc_data
          - name: pv-smrs
            mountPath: /ericsson/tor/smrs
          - name: pv-alex
            mountPath: /ericsson/enm/alex
      volumes:
        - name: pv-gp
          configMap:
            name: gpcloud
        - name: pv-data
          persistentVolumeClaim:
            claimName: data
        - name: pv-configmgt
          persistentVolumeClaim:
            claimName: config-mgt
        - name: pv-pm1
          persistentVolumeClaim:
            claimName: pmic1
        - name: pv-pm2
          persistentVolumeClaim:
            claimName: pmic2
        - name: pv-pmlinks
          persistentVolumeClaim:
            claimName: pmlinks
        - name: pv-upgind
          persistentVolumeClaim:
            claimName: upgind
        - name: pv-dumps
          persistentVolumeClaim:
            claimName: dumps
        - name: pv-mdt
          persistentVolumeClaim:
            claimName: mdt
        - name: pv-netlog
          persistentVolumeClaim:
            claimName: netlog
        - name: pv-custom
          persistentVolumeClaim:
            claimName: custom
        - name: pv-dlms
          persistentVolumeClaim:
            claimName: dlms
        - name: pv-batch
          persistentVolumeClaim:
            claimName: batch
        - name: pv-norollback
          persistentVolumeClaim:
            claimName: norollback
        - name: pv-ddcdata
          persistentVolumeClaim:
            claimName: ddcdata
        - name: pv-smrs
          persistentVolumeClaim:
            claimName: smrs
        - name: pv-alex
          persistentVolumeClaim:
            claimName: alex
        - name: pv-shared
          persistentVolumeClaim:
            claimName: shared

