apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    name: consul
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: https
      port: 8443
      targetPort: 8443
    - name: rpc
      port: 8400
      targetPort: 8400
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
    - name: consuldns
      port: 8600
      targetPort: 8600
  selector:
    app: consul

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-server
data:
  server.json: |
    {
        "bind_addr": "0.0.0.0",
        "bootstrap_expect": 3,
        "server": true,
        "datacenter": "dc1",
        "disable_remote_exec": true,
        "data_dir": "/ericsson/data",
        "log_level": "INFO",
        "domain": "enm",
        "autopilot":{
          "cleanup_dead_servers": false
        },
        "ports":{
          "dns": 53
        },
        "dns_config":{
          "only_passing": true
        },
        "raft_protocol": 3,
        "rejoin_after_leave": true,
        "disable_update_check": true,
        "client_addr": "0.0.0.0"
    }

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
  serviceName: consul
  replicas: 3
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/eric-enmsg-serviceregistry
        ports:
          - containerPort: 8500
          - containerPort: 8443
          - containerPort: 8400
          - containerPort: 8301
          - containerPort: 8302
          - containerPort: 8600
          - containerPort: 53
          - containerPort: 80
          - containerPort: 443
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command: ["consul"]
        args:
          - "agent"
          - "-advertise=$(POD_IP)"
          - "-node=$(POD_NAME)"
          - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
          - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
          - "-retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
          - "-config-dir=/ericsson/consul/config"
        volumeMounts:
          - name: data
            mountPath: /ericsson/data
          - name: config
            mountPath: /ericsson/consul/config
      volumes:
        - name: config
          configMap:
            name: consul-server
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: "erikube-cinder"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
