apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossiprouter-remoting
spec:
  selector:
    matchLabels:
      app: gossiprouter-remoting
  replicas: 1
  template:
    metadata:
      labels:
        app: gossiprouter-remoting
    spec:
      containers:
      - name: gossiprouter-remoting
        resources:
          requests:
            memory: "2Gi"
        image: 152254703525.dkr.ecr.eu-west-1.amazonaws.com/eirepoc1-registry:gossip-rhel6basejava8
        imagePullPolicy: Always
#        livenessProbe:
#          httpGet:
#            port: 12987
#          initialDelaySeconds: 300
#          timeoutSeconds: 10
#          periodSeconds: 30
#          failureThreshold: 2
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            value: "12001"
          - name: GOSSIP_ROUTER_USAGE
            value: "remoting"
        ports:
          - containerPort: 12001
          - containerPort: 12002
          - containerPort: 9990
          - containerPort: 8009
          - containerPort: 9999
          - containerPort: 8080
          - containerPort: 4447
          - containerPort: 9999
        args:
          - -bind_addr $(POD_IP) -port $(PORT)
        volumeMounts:
          - name: pv-gp
            mountPath: /gp
          - name: pv-data
            mountPath: /ericsson/tor/data
          - name: pv-dumps
            mountPath: /ericsson/enm/dumps
          - name: pv-norollback
            mountPath: /ericsson/no_rollback
      volumes:
        - name: pv-gp
          configMap:
            name: gpcloud
        - name: pv-data
          persistentVolumeClaim:
            claimName: data
        - name: pv-norollback
          persistentVolumeClaim:
            claimName: norollback
        - name: pv-dumps
          persistentVolumeClaim:
            claimName: dumps

