apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ index .Values "replicas-<CHARTNAME>" }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
{{- if ne .Values.deploymentStrategy "RollingUpdate" }}
    rollingUpdate: null
{{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
{{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ tpl .Values.affinity . | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if or .Values.extraInitContainers .Values.waitInitContainer.enabled }}
      initContainers:
{{- if .Values.extraInitContainers }}
{{ toYaml .Values.extraInitContainers | indent 6 }}
{{- end }}
{{- if .Values.waitInitContainer.enabled }}
      - name: {{ .Values.service.name }}-wait
        image: "{{ .Values.image.repository }}:{{ .Values.waitInitContainer.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy | quote }}
        command: {{ .Values.waitInitContainer.command }}
        env:
         - name: NAMESPACE
           valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
{{- end }}
{{- end }}
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy | quote }}
        command: {{ .Values.image.command }}
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
{{- if .Values.sidecarContainers }}
{{ toYaml .Values.sidecarContainers | indent 6 }}
{{- end }}
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 10 }}
{{- end }}
{{- if .Values.extraPorts.enabled }}
        ports:
{{ .Files.Get "config/containerPorts.txt" | indent 10 }}
{{- end }}
{{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            port: {{ .Values.readinessProbe.httpPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
{{- end }}
{{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            port: {{ .Values.readinessProbe.httpPort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
{{- end }}
{{- if or .Values.persistence.enabled .Values.configMaps.enabled .Values.extraVolumeMounts.enabled }}
        volumeMounts:
{{- end }}
{{- if .Values.persistence.enabled }}
        - name: pv-{{ template "<CHARTNAME>.name" . }}
          mountPath: {{ .Values.persistence.mountPath }}
{{- end }}
{{- if .Values.configMaps.enabled }}
        - name: configurations
          mountPath: {{ .Values.configMaps.mountPath }}
{{- end }}
{{- if .Values.extraVolumeMounts.enabled }}
{{ .Files.Get "config/volumeMounts.txt" | indent 8 }}
{{- end }}
      volumes:
{{- if .Values.configMaps.enabled }}
      - name: configurations
        configMap:
          name: {{ .Values.configMaps.name }}
{{- end }}
{{- if .Values.extraVolumes.enabled }}
{{ .Files.Get "config/volumes.txt" | indent 6 }}
{{- end }}
{{- if .Values.persistence.enabled }}
      - name: pv-{{ template "<CHARTNAME>.name" . }}
        persistentVolumeClaim:
          claimName: {{ template "<CHARTNAME>.name" . }}
{{- end }}
