kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: efs-provisioner-multi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner-multi
    spec:
      containers:
        - name: efs-provisioner-multi
          image: quay.io/external_storage/efs-provisioner:v0.1.0
          env:
            - name: FILE_SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: file.system.id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: aws.region
            - name: PROVISIONER_NAME
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: provisioner.name
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
            - name: pv-volume-multi
              mountPath: /persistentvolumes-multi
      volumes:
        - name: pv-volume
          nfs:
            server: fs-b2f87af9.efs.us-east-1.amazonaws.com
            path: /pvc
        - name: pv-volume-multi
          nfs:
            server: fs-a073e2eb.efs.us-east-1.amazonaws.com
            path: /pvc2
