apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbasedclient-deployment
spec:
  selector:
    matchLabels:
      app: eventbasedclient
  replicas: 1
  template:
    metadata:
      labels:
        app: eventbasedclient
    spec:
      containers:
      - name: eventbasedclient
        resources:
          requests:
            memory: "2Gi"
        image: dockerregistry:5000/rhel6-eventbasedclient
        ports:
          - containerPort: 58178
          - containerPort: 58179
          - containerPort: 54500
          - containerPort: 58180
          - containerPort: 50692
          - containerPort: 63045
          - containerPort: 63013
          - containerPort: 9990 
          - containerPort: 58151
          - containerPort: 59560
          - containerPort: 3528 
          - containerPort: 63113
          - containerPort: 8009 
          - containerPort: 59530
          - containerPort: 57419
          - containerPort: 56139
          - containerPort: 55500
          - containerPort: 59500
          - containerPort: 58156
          - containerPort: 58157
          - containerPort: 57422
          - containerPort: 9999 
          - containerPort: 63056
          - containerPort: 8080 
          - containerPort: 52689
          - containerPort: 58161
          - containerPort: 57425
          - containerPort: 58162
          - containerPort: 58163
          - containerPort: 58164
          - containerPort: 56212
          - containerPort: 58165
          - containerPort: 58166
          - containerPort: 58167
          - containerPort: 59000
          - containerPort: 58168
          - containerPort: 54200
          - containerPort: 58169
          - containerPort: 57113
          - containerPort: 63034
          - containerPort: 58170
          - containerPort: 58171
          - containerPort: 59100
          - containerPort: 58172
          - containerPort: 58173
          - containerPort: 58174
          - containerPort: 58175
          - containerPort: 50719
          - containerPort: 4447 
          - containerPort: 54400
          - containerPort: 58176
          - containerPort: 59200
          - containerPort: 58177
          - containerPort: 54689
          - containerPort: 7600
          - containerPort: 57600
          - containerPort: 9443
          - containerPort: 4712
          - containerPort: 4713
          - containerPort: 3528
          - containerPort: 3529
          - containerPort: 12001
          - containerPort: 12002
          - containerPort: 55501
          - containerPort: 55500
          
        command: ["/bin/bash"]
        args: ["-c","while true; do sleep 10;done"]
        volumeMounts:
          - name: data
            mountPath: /ericsson/tor/data
          - name: mdt
            mountPath: /etc/opt/ericsson/ERICmodeldeployment      
          - name: home
            mountPath: /home/shared
          - name: custom
            mountPath: /ericsson/custom
          - name: dumps
            mountPath: /ericsson/enm/dumps
          - name: dlms
            mountPath: /ericsson/enm/dlms/history/data
          - name: batch
            mountPath: /ericsson/batch
          - name: norollback
            mountPath: /ericsson/no_rollback
          - name: configmgt
            mountPath: /ericsson/config_mgt
          - name: pm1
            mountPath: /ericsson/pmic1
          - name: pm2
            mountPath: /ericsson/pmic2
          - name: pmlinks
            mountPath: /ericsson/symvol
          - name: upgind
            mountPath: /ericsson/configuration_management/UpgradeIndependence
      volumes:
        - name: configmgt
          nfs:
            server: nfsconfigmgt
            path: "/ericsson/config_mgt"
        - name: pm1
          nfs:
            server: nfspm1
            path: "/ericsson/pm1"
        - name: pm2
          nfs:
            server: nfspm2
            path: "/ericsson/pm2"
        - name: pmlinks
          nfs:
            server: nfspmlinks
            path: "/ericsson/pmlinks1"
        - name: upgind
          nfs:
            server: nfsupgind
            path: "/ericsson/config_mgmt_upgind"
        - name: data
          nfs:
            server: nfsdata
            path: "/ericsson/data"
        - name: dumps
          nfs:
            server: nfshcdumps
            path: "/ericsson/hcdumps"
        - name: mdt
          nfs:
            server: nfsmdt
            path: "/ericsson/mdt"
        - name: home
          nfs:
            server: nfshome
            path: "/ericsson/home"
        - name: custom
          nfs:
            server: nfscustom
            path: "/ericsson/custom"
        - name: dlms
          nfs:
            server: nfsdlms
            path: "/ericsson/dlms"
        - name: batch
          nfs:
            server: nfsbatch
            path: "/ericsson/batch"
        - name: norollback
          nfs:
            server: nfsnorollback
            path: "/ericsson/no_rollback"
