apiVersion: v1
kind: Service
metadata:
  name: sentinel
spec:
  clusterIP: None
  ports:
    - name: sentinel-port1
      port: 5093
      targetPort: 5093
    - name: sentinel-port2
      port: 5099
      targetPort: 5099
    - name: ssh
      port: 22
      targetPort: 22
  selector:
    app: sentinel
---
apiVersion: v1
kind: Service
metadata:
  name: sentinelhost
spec:
  clusterIP: None
  ports:
    - name: sentinel-port1
      port: 5093
      targetPort: 5093
    - name: sentinel-port2
      port: 5099
      targetPort: 5099
    - name: ssh
      port: 22
      targetPort: 22
  selector:
    app: sentinel
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentinel
spec:
  selector:
    matchLabels:
      app: sentinel
  serviceName: sentinel
  replicas: 1
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      containers:
      - name: sentinel
        image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/eric-enmsg-sentinel
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            port: 12987
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 2
        ports:
          - containerPort: 22
          - containerPort: 5093
          - containerPort: 5099
          - containerPort: 4447
        command: ["/bin/sh", "-c"]
        args:
          - bash /var/tmp/sentinel_config.sh; while true; do sleep 300;done;
        volumeMounts:
          - name: nfs-gp
            mountPath: /gp
          - name: nfs-data
            mountPath: /ericsson/tor/data
          - name: nfs-dumps
            mountPath: /ericsson/enm/dumps                
          - name: sentinel-lic
            mountPath: /ericsson/sentinel_lic
      volumes:
        - name: nfs-gp
          configMap:
            name: gpcloud
        - name: nfs-data
          persistentVolumeClaim:
            claimName: nfs-data
        - name: nfs-dumps
          persistentVolumeClaim:
            claimName: nfs-hcdumps
  volumeClaimTemplates:
    - metadata:
        name: sentinel-lic
      spec:
        storageClassName: "erikube-rbd"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
