apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: {{ template "stateless-integration.registryUrl" . }}/{{ .Values.imageCredentials.repoPath }}/{{ index .Values "images" "stateless-integration" "name" }}:{{ index .Values "images" "stateless-integration" "tag" }}
        imagePullPolicy: Always
        command: {{ index .Values "images" "stateless-integration" "command" }}